project_id = "uypsjomkikkvbmutsjkt"

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-booking-checkout]
verify_jwt = false

[functions.get-booking-status]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false