// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uypsjomkikkvbmutsjkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cHNqb21raWtrdmJtdXRzamt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0OTIwOTYsImV4cCI6MjA4OTA2ODA5Nn0.lX6kOF-uFOa903Z0ksG2tJ4xW2AspSnJjdjWjet6Heo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});